site_name: Chang's Notes
site_url: https://lceoliu.github.io/SP26_SI100B_Tutorial/
theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 深色模式
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: 浅色模式
  font:
    text: Noto Sans
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

hooks:
  - hooks/gen_tutorials.py

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  giscus:
    repo: "Lceoliu/SP26_SI100B_Tutorial"
    repo_id: "R_kgDORtj6cw"
    category: "Q&A"
    category_id: "DIC_kwDORtj6c84C5A60"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "bottom"
    lang: "zh-CN"
    theme_light: "light"
    theme_dark: "transparent_dark"
    loading: "lazy"

nav:
  - 首页: index.md
  - 教程:
      - 复杂度与二分搜索: hw1/bin_complexity.md
